AWSTemplateFormatVersion: 2010-09-09
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: ECS-Cluster
      Tags:
        - Key: environment
          Value: dev
          
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      
      Cpu: 2048
      Memory: 4096
      ContainerDefinitions: 
        - 
          Name: "my-app"
          Image: "amazon/amazon-ecs-sample"
          Cpu: 256
          EntryPoint: 
            - "/usr/sbin/apache2"
            - "-D"
            - "FOREGROUND"
          Memory: 512
          Essential: true
        - 
          Name: "busybox"
          Image: "busybox"
          Cpu: 256
          EntryPoint: 
            - "sh"
            - "-c"
          Memory: 512 

